version: '3'

services:
  frontend:
    image: eeacms/eea-storybook
    ports:
    - "${FRONTEND:-4000}:4000"
    depends_on:
    - backend
    environment:
      PORT: "${FRONTEND:-4000}"
      RAZZLE_DEV_PROXY_API_PATH: "http://localhost:${BACKEND:-8080}/Plone"

  backend:
    image: eeacms/plone-backend
    depends_on:
      - memcached
    ports:
      - '${BACKEND:-8080}:8080'
    environment:
      CORS_ALLOW_ORIGIN: 'http://localhost:3000,http://localhost:${FRONTEND:-4000}'
      SITE: 'Plone'
    volumes:
      - ./data:/data

  memcached:
    image: memcached
    command:
      - '-m'
      - '1024'
