# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} to build storybook website
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Push Storybook build changes
      run: |
           git switch -
           git checkout -b ${{ github.head_ref }}
           git branch --set-upstream-to=origin/${{ github.head_ref }} ${{ github.head_ref }}
           git branch -a
           npm install -g mrs-developer
           yarn develop
           yarn install
           yarn build-storybook
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add docs
           git diff --staged --quiet || git commit -m "Autobuild of storybook docs"
           git push -u origin ${{ github.head_ref }}
